CREATE TABLE users (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    ip VARCHAR(36) NOT NULL UNIQUE,
    user_agent VARCHAR(200) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
