CREATE TABLE reporting_reasons (
    id SERIAL NOT NULL PRIMARY KEY,
    reason VARCHAR(250) NOT NULL UNIQUE,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
